export enum RoutePath {
    HOME = "/",
    ANIMAL = "/animal",
    CREATE_ANIMAL = "/animal/create",
    ANIMAL_DETAILS_PAGE = "/animal/details/:id",
    ARTICLE = "/article",
    CREATE_ARTICLE = "/article/create",
    ARTICLE_DETAILS_PAGE="/article/details/:id",
    NOTIFICATION_ERRORS = "/notification-errors",
    NOT_FOUND = "*",
    TAG_CREATE_PAGE = "/tags/create",
    TAG_DETAILS_PAGE = "/tags/details/:id",
    TAG_LIST_PAGE = "/tags",
    LOGIN = "/login",
    REGISTER = "/register",
    GMAIL_AUTH = "/auth/gmail",
    GMAIL_SET_PASSWORD = "/auth/gmail/set-password",
    FORGOT_PASSWORD = "/forgot-password",
    LOGOUT = "/logout",
    ACTIVATE_ACCOUNT = "/activate-account/:token",
    PASSWORD_RESET = "/password-reset/:token",
    USERS = "/users",
    USERS_CREATE = "/users/create",
    USERS_DETAILS = "/users/details/:id",
    ACTIVITY_LOGS = "/activities",
    ACTIVITY_LOGS_DETAILS = "/activities/details/:id",
    MY_ACTIVITY_LOGS = "/activities/myactivities",
}
