import {ApiException} from "../commons/api-exception/ApiException";

export const axiosHandledExceptions: string[] = [
    ApiException.AUTHENTICATION_EXCEPTION,
    ApiException.USER_ACCOUNT_NOT_ACTIVATED_EXCEPTION,
    ApiException.USER_ALREADY_EXISTS,
    ApiException.GMAIL_AUTHENTICATION_EXCEPTION,
    ApiException.UNPRIVILEGED_GMAIL_DOMAIN_EXCEPTION,
    ApiException.ACTIVATE_ACCOUNT_TOKEN_ALREADY_USED_EXCEPTION,
    ApiException.PASSWORD_RESET_TOKEN_ALREADY_USED_EXCEPTION,
    ApiException.PASSWORD_RESET_TOKEN_EXPIRED_EXCEPTION,
    ApiException.PASSWORD_RESET_GMAIL_AUTH_EXCEPTION,
    ApiException.GMAIL_LOGIN_PASS_AUTH_DISABLED_EXCEPTION,
    ApiException.USER_NOT_FOUND_BY_EMAIL_EXCEPTION,
    ApiException.TAG_ALREADY_EXISTS_EXCEPTION
]